server:
  port: 8080

spring:

  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

security:
  basic:
    enabled: false
